# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(name: 'Tyler', email: 'lksevans12@gmail.com', password: 'Lulu123456')
User.create!(name: 'Tiffany',email: 'lulu@me.com', password: 'Spanish4537')
User.create!(name: 'Lulu',email: 'laura@me.com', password: 'Tyler1234', admin:false)

GearCat.create!(category_name: 'Kites')
GearCat.create!(category_name: 'Boards')
GearCat.create!(category_name: 'Accessories')

Admin.create!(user_id:1)

Gear.create!(name: 'Kiteboarding Kite 1', description: 'Kiteboarding Kite 1 is nice.', gear_cat_id:1)

Blog.create!(title: 'Kiteboarding Blog', user_id:1)
Blog.create!(title: 'Landkiting Blog',user_id:2)



Post.create!(title: 'Blog 1', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:1, user_id:1, featured:true)

Post.create!(title: 'Blog 2', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.',blog_id:1, user_id:1)

Post.create!(title: 'Blog 3', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.',blog_id:1, user_id:1)

Post.create!(title: 'Blog 4', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.',blog_id:2, user_id:1)

Post.create!(title: 'Blog 5', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.',blog_id:1, user_id:2)

Post.create!(title: 'Blog 6', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.',blog_id:2, user_id:1)

Post.create!(title: 'Blog 7', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:1, user_id:1)

Post.create!(title: 'Blog 8', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:1, user_id:2)

Post.create!(title: 'Blog 9', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:2, user_id:1)

Post.create!(title: 'Blog 10', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:1, user_id:2)

Post.create!(title: 'Blog 11', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:2, user_id:1)
Post.create!(title: 'Blog 12', body: 'Vestibulum eleifend ipsum ligula, nec aliquam neque malesuada non. Vestibulum dapibus tempus quam eu tempor. Vestibulum ac magna viverra, laoreet quam id, placerat magna. Sed luctus justo nulla, id rhoncus augue venenatis accumsan. Aenean nec lectus nec tortor gravida pharetra vitae sit amet metus. Nunc non mauris ornare, mattis lorem nec, fringilla leo. Nullam at porta sapien.

Integer gravida porttitor enim, eget pulvinar ex vulputate in. Sed sed nunc porttitor, porttitor nulla sit amet, rhoncus odio. Nunc at consequat lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam et nulla sit amet orci dignissim eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tristique nibh sit amet ex tincidunt congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed euismod sed elit eget fringilla.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum pretium congue. Nulla gravida, orci eu condimentum placerat, dui arcu semper dui, a lacinia massa orci non leo. Etiam a condimentum arcu. Morbi sit amet sapien dignissim, molestie massa ut, pharetra nisi. Phasellus posuere tortor eget magna fermentum tristique at et libero. In vitae odio eleifend, ullamcorper enim eu, viverra lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin euismod sollicitudin accumsan.', blog_id:1, user_id:1)
